/**
 * Arazzo export — serialize workflows to Arazzo 1.0.0 specification format.
 *
 * Arazzo is the OpenAPI Initiative standard for describing API workflow sequences.
 * https://spec.openapis.org/arazzo/latest.html
 */

import type { Workflow, WorkflowStep, DataBinding } from '../types'

// === Arazzo document types ===

export interface ArazzoDocument {
  arazzo: '1.0.0'
  info: {
    title: string
    version: string
    description?: string
  }
  sourceDescriptions: ArazzoSourceDescription[]
  workflows: ArazzoWorkflow[]
}

interface ArazzoSourceDescription {
  name: string
  url: string
  type: 'openapi' | 'arazzo'
}

interface ArazzoWorkflow {
  workflowId: string
  summary: string
  description?: string
  steps: ArazzoStep[]
}

interface ArazzoStep {
  stepId: string
  operationId: string
  description?: string
  outputs?: Record<string, string>
  parameters?: ArazzoParameter[]
}

interface ArazzoParameter {
  name: string
  in: string
  value: string
}

// === Conversion ===

/**
 * Convert a DataBinding to an Arazzo runtime expression.
 * e.g., { sourceField: 'id', targetParam: 'userId' }
 * → value: "$steps.step_0.outputs.id"
 */
function bindingToExpression(binding: DataBinding, sourceStepId: string): string {
  return `$steps.${sourceStepId}.outputs.${binding.sourceField}`
}

/**
 * Convert a WorkflowStep to an ArazzoStep.
 */
function toArazzoStep(
  step: WorkflowStep,
  index: number,
  prevStepId?: string,
): ArazzoStep {
  const stepId = `step_${index}`

  const arazzoStep: ArazzoStep = {
    stepId,
    operationId: step.operationId,
    description: `${step.role} step`,
  }

  // Add output declarations for non-final steps
  // (so subsequent steps can reference them)
  if (index === 0 || step.role === 'list' || step.role === 'search' || step.role === 'create') {
    arazzoStep.outputs = {
      // Declare that response body is available
      body: '$response.body',
    }
  }

  // Add parameter bindings from previous step
  if (prevStepId && step.inputBindings.length > 0) {
    arazzoStep.parameters = step.inputBindings.map(binding => ({
      name: binding.targetParam,
      in: binding.targetParamIn,
      value: bindingToExpression(binding, prevStepId),
    }))
  }

  return arazzoStep
}

/**
 * Convert an internal Workflow to an ArazzoWorkflow.
 */
function toArazzoWorkflow(workflow: Workflow): ArazzoWorkflow {
  const steps: ArazzoStep[] = []

  for (let i = 0; i < workflow.steps.length; i++) {
    const step = workflow.steps[i]!
    const prevStepId = i > 0 ? `step_${i - 1}` : undefined
    steps.push(toArazzoStep(step, i, prevStepId))
  }

  return {
    workflowId: workflow.id,
    summary: workflow.name,
    description: workflow.description,
    steps,
  }
}

/**
 * Serialize workflows to an Arazzo 1.0.0 document.
 *
 * @param workflows - Inferred workflows to export
 * @param apiTitle - Title of the source API
 * @param specUrl - URL of the source OpenAPI spec
 * @returns Arazzo document object (serialize with JSON.stringify or a YAML library)
 */
export function toArazzo(
  workflows: Workflow[],
  apiTitle: string,
  specUrl: string,
): ArazzoDocument {
  return {
    arazzo: '1.0.0',
    info: {
      title: `${apiTitle} Workflows`,
      version: '1.0.0',
      description: `Auto-inferred workflows for ${apiTitle}. Generated by @api2aux/workflow-inference.`,
    },
    sourceDescriptions: [
      {
        name: 'source-api',
        url: specUrl,
        type: 'openapi',
      },
    ],
    workflows: workflows.map(toArazzoWorkflow),
  }
}
